chore: another minor change

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -71,12 +71,12 @@ jobs:
           git config user.email "${{ github.actor}}@users.noreply.github.com"
 
           # output summary changes
-          # echo "Echo repo changes"
-          # git diff-index --stat HEAD
-          # git --no-pager diff --compact-summary
-          # echo "After stat command $?"
-          # git diff-index --quiet --exit-code HEAD; echo "Exit code $?"
+          echo "Echo repo changes"
+          git diff-index --stat HEAD
+          git --no-pager diff --compact-summary
+          echo "After diff command $?"
           
+          # git diff-index --quiet --exit-code HEAD; echo "Exit code $?"
           # git diff-index --quiet --exit-code HEAD && echo "with && SDK changes"
           # git diff-index --quiet --exit-code HEAD || echo "with || SDK changes"
           
