another try

diff --git a/.github/workflows/publish.yaml b/.github/workflows/publish.yaml
--- a/.github/workflows/publish.yaml
+++ b/.github/workflows/publish.yaml
@@ -73,13 +73,11 @@ jobs:
           # output summary changes
           echo "Echo repo changes"
           git diff-index --stat HEAD
-          git diff-index --quiet HEAD; echo "Exit code $?"
           git diff-index --quiet --exit-code HEAD; echo "Exit code $?"
+          # git diff-index --quiet HEAD; echo "Exit code $?"
           
-
-          
-          git diff-index --quiet --exit-code HEAD || echo "SDK changes 1"
-          git diff-index --quiet --exit-code HEAD && echo "SDK changes 2"
+          git diff-index --quiet --exit-code HEAD && echo "with && SDK changes"
+          git diff-index --quiet --exit-code HEAD || echo "with || SDK changes"
           
           # publish SDK if required
           if [ "$ENVIRONMENT" == "production" ]
